### ISSUE TITLE
Dark Mode Theme 

### ISSUE THREAD

**Issue by blackrosedragon2** [Adversarial-Deep-Learning/adversarial-deep-learning.github.io#3]
Create a generic settings page (for future additions other settings), in which users are able to toggle between Dark/Light modes:

- [ ] Generic Settings Page (Maybe a tabular format)
- [x] Dark mode toggle option

**Comment by git-pi-e** [comment]
I think can we should implement scss to the website acc to following docs for better contribution: 
https://jekyllrb.com/docs/assets/

**Comment by blackrosedragon2** [comment]
Yes, we can add all of the necessary folders, you can also check out the way they've implemented it for the theme we're using from here: <https://pmarsceill.github.io/just-the-docs/docs/configuration/#color-scheme>. Do you want to have a go at it?

**Comment by git-pi-e** [comment]
Yeah I'll try this right after the landing page

**Comment by git-pi-e** [comment]
Okay, I added a settings page and a Color change toggle button acc to JTD styling, but problem with it is, it resets on reload, hence once it enters the dark mode and we shift to another page, it's back to original. So currently website wide dark mode is possible.

**Comment by git-pi-e** [comment]
So I've added the toggle to the header so that it can be accessible from any page and the default mode is dark.

**Comment by blackrosedragon2** [comment]
Cool that works!

**Comment by git-pi-e** [comment]
The config property of Jekyll actually force-resets the color mode on refresh. So probably the reader may need to switch it on reading for every page. For the same purpose I had put in in the header
